### PR TITLE
Update Rollbar.NetCore.AspNet.csproj

### PR DESCRIPTION
**Pull request by chamamo**
Add net framework support
Necessary when we want to use RollBar in asp.net project targetting netframwork but using .Net core host

### CODE REVIEW

**Comment by akornich** [comment]
@chamamo, Rollbar.NetCore.AspNet explicitly builds .Net Core targets, use build results of the target close matching your .NET Core host version. Why would you want to build .NET 4.6.1 target and use it within a .NET Core host when you already have a build targeting .NET Core specifically?

**Comment by chamamo** [comment]
My solution contains many assemblies that still targetting net461 (legacy) and I can't convert it to netstandard at this time. That's why in my web api project is not in core, It still targetting net461 but hosting with microsoft.aspnetcore.
By adding the net461 you will also support solutions like mine that are migrating from netframework to core (but not completely)

**Comment by chamamo** [comment]
I will cancel this PR and create another with a successfull build

**Comment by akornich** [comment]
@chamamo , in this case i would recommend adding `netstandard2.0` target instead of `net461` and of cause making the build to succeed :)

**Comment by chamamo** [comment]
I repaced all values by netstandard2.0

**Pull request merged**
