### PR TITLE
Single file app fix

### PR DESCRIPTION
**Pull request by Janek91**
## Description of the change
Fixed issue with single file applications in .NET 5. As ExecutingAssembly.Location will always return emty string - it is recommended to use AppContext.BaseDirectory to get current app executable directory path.

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by Janek91** [comment]
That's strange. On my local machine all unit tests have passed.

**Comment by Janek91** [comment]
image

**Comment by akornich** [comment]
> That's strange. On my local machine all unit tests have passed.

@Janek91 , you are good. It looks like there was an issue with Internet connectivity for the CI pipeline. I just reran the CI and it passed all tests. Thank you!

**Review by akornich — APPROVED** [review]
@Janek91 , thank you!

**Pull request merged**
