### PR TITLE
Fixing error title so it reflects that of the exception being thrown

### PR DESCRIPTION
**Pull request by cvallance**
Fixed the unhandled error title to be that of the exception that is being thrown. Somewhat related to this issue:
https://github.com/rollbar/Rollbar.NET/issues/346

Also
- I think I fixed a bug where if you set `maxItems` the exception handler would never send the message
- Removed RollbarMiddlewareException because there was no need for it potentially may have lost stacktrace by throwing a new error

### CODE REVIEW

**Comment by cvallance** [comment]
Sorry @akornich I didn't assign you at the start and now it appears I can't edit it to assign you, most likely pebkac... but anyway, if you could take a look at this, that would be great.

**Comment by cvallance** [comment]
@akornich Sorry, just making sure this on your radar... let me know if it's not appropriate and/or it needs tweaking.

**Comment by akornich** [comment]
@cvallance , thanks for submitting the PR. We are having an internal discussion regarding the validity of the change from the system point of view. At the moment it looks like we can not take it as is since it will be causing a loss of some valuable context for many (if not most) of our users. The discussion now is mainly around having your change as optional/configurable only when preferred by a specific user.

**Comment by akornich** [comment]
since we can not accept this PR as is - rejecting/closing it for now. we may include similar behavior offered by this PR but as a configurable option only.

**Comment by cvallance** [comment]
Sorry, just reviewing this 1 year later as we look to potentially move our dotnet stuff to join our python stuff in rollbar or vice versa.

@akornich Can you please elaborate on what you mean by "causing a loss of some valuable context fo many (if not most) of our users"...?

**Pull request closed without merging**
