### PR TITLE
Release candidate v3.14.0

### LINKED ISSUE #564: Add ILogger LoggerName to details in Rollbar
**Is your feature request related to a problem? Please describe.**
I cannot always tell where an event is coming from in Rollbar.

**Describe the solution you'd like**
It would be very useful if Rollbar would include the loggername from the .Net Core ILogger interface

### LINKED ISSUE #565: Factor out code duplication between the NetPlatformExtensions and NetCore.AspNET modules
there are a few duplicated classes in both modules that were a leftover from the time when we introduced the NetPlatformExtensions module

### LINKED ISSUE #567: Fix dependencies of Sample.NetCore.ConsoleApp

### LINKED ISSUE #568: Remove unused legacy dependencies of Rollbar.NetCore.AspNet

### PR DESCRIPTION
**Pull request by akornich**
The two issues/work-items addressed by the PR are actually related since factoring out the code duplication is a prerequisite for the other item (otherwise we would have to handle the second item in two code places in two separate SDK modules identically).

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

>feat: resolve #564: Add ILogger LoggerName to details in Rollbar.
>refactor: resolve #565: Factor out code duplication between the NetPlatformExtensions and NetCore.AspNET modules.
>refactor: resolve #568: Remove unused legacy dependencies of Rollbar.NetCore.AspNet.
>docs: resolve #567: Fix dependencies of Sample.NetCore.ConsoleApp.

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [x] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Review by waltjones — APPROVED** [review]
As far as I can tell this looks good, but there are things that make it harder to read than necessary.

* There are a number of places where version numbers of dependencies are bumped in the "refactor" commits. Are those directly related to the refactor? Or just happen to be in the same commit? If the former, comments in the PR description would be helpful. If the latter, why not put those things in their own commit?

* If the "refactor" commits are all one logical piece of work, why not squash them so they can be reviewed as a whole, while still separate from the other unrelated changes?

* The version bump (3.14.0) in SdkCommon.csproj should have its own commit and that commit should get the version tag in git. Why hide it in an unrelated commit?

**Comment by akornich** [comment]
@waltjones , thanks for the review and actionable feedback!

- the incremented dependencies versions were "as-discovered" fixes of build warnings while doing the refactoring (one of the primary reasons for this PR). Even better news, the dependencies can be completely removed at this point (as the result of the recent refactoring steps).
- by default, I do prefer not to squash my commits (since often it provides a better perspective on how the total changes evolved). The final total change (as a squashed equivalent) is always available as part of the closed PR metadata.
- it makes more sense to properly increment the version with the very first commit following the last available release. And of cause, it should be updated with every subsequent commit of "higher-impact" whenever applicable. This is if we are talking about updating the product version that is part of product distributable metadata. On the other hand, a corresponding release version git tag is introduced right at the point of product release as an in-time freeze of the product codebase corresponding to that release. Does it make sense?

**Comment by waltjones** [comment]
How do you know whether it's going to be a point or minor release before any of the work for the next release?

**Comment by akornich** [comment]
Simply like this: 
Since you "properly increment the version with **the very first commit** following the last available release", you already know the impact of that change. Then you might have to update the version based on "it should be updated with every subsequent commit of a "higher-impact" whenever applicable." 
For example, the first commit after the last release is a hot-fix - so you increment the hot-fix portion of the version triplet. Then if you subsequently at some point commit changes involving a new add-on feature - you increment the minor release and reset the hot-fix part to `0`.

**Pull request merged**
